### ISSUE TITLE
[Support] Initializing logging in the newest version of SAML2

### ISSUE THREAD

**Issue by TheDarkTrumpet** [i8beef/SAML2.Logging.Log4Net#1]
Hello,

I read through your documentation here, and it specifies adding a new section (or using existing) and adding the line for logging.

Doing a copy/paste of what you had resulted in an error, and I assumed that it had to do with the configuration section not being defined.  I tried a few things.  First, I tried to point it in the following ways:

`<section name="SAML20Federation" type="SAML2.Logging.Log4Net.Log4NetInternalLogger, Saml2.Logging.Log4Net"/>` and with Log4NetLoggerFactory.  Both "compile" fine, but don't appear to be logging.

I then assumed perhaps that the section name you meant was "saml2", like in your other documentation.  So I tried pasting that line there.  While it compiles fine, logging doesn't happen.

I verified that I have a file output logger, set to "ALL", and have already logged information into that file from my webapp.

Thanks for your help in this.  Also, thanks for the documentation.  Many projects don't have documentation.  I'm currently implementing SAML2 auth against Shibboleth, and am having a problem loading metadata.  I noticed the main library had logging calls, so am trying to make use of that with log4net so I can figure out where it's looking and why metadata isn't loading.

**Comment by i8beef** [comment]
It should be in the `<saml2>` section. I updated the docs here. It should look like this:https://github.com/i8beef/SAML2.Logging.Log4Net/wiki

**Comment by TheDarkTrumpet** [comment]
Thanks for the quick reply.  I'll work on this some more.  It's still not logging, getting a type initialization error, but will mess with it some more.  Thanks again for the quick reply and fix to the documentation.
